In [2]:
import numpy as np
import tensorflow.keras as keras
import pandas as pd

In [3]:
concrete_data = pd.read_csv("https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0101EN/labs/data/concrete_data.csv")

concrete_data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [4]:
concrete_data.shape

(1030, 9)

In [5]:
concrete_data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

In [6]:
concrete_data_cols = concrete_data.columns

concrete_data_cols

Index(['Cement', 'Blast Furnace Slag', 'Fly Ash', 'Water', 'Superplasticizer',
       'Coarse Aggregate', 'Fine Aggregate', 'Age', 'Strength'],
      dtype='object')

In [7]:
predictors = concrete_data.drop(columns=['Strength'])

target = concrete_data['Strength']

In [8]:
predictors.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

In [9]:
target.head()

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
Name: Strength, dtype: float64

In [10]:
predictors_norm = (predictors - predictors.mean() ) / predictors.std()
predictors_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

In [11]:
predictors_norm.shape[0]

1030

In [17]:
n_cols = predictors_norm.shape[1]

In [18]:
from keras.models import Sequential
from keras.layers import Dense, Input

In [19]:
def regression_model():
    model = Sequential()
    model.add(Input(shape=(n_cols,)))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(1))

    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

In [20]:
model = regression_model()

model.fit(predictors_norm, target, validation_split=0.3, epochs=100, verbose=2)

Epoch 1/100
23/23 - 3s - 138ms/step - loss: 1667.6101 - val_loss: 1177.4265
Epoch 2/100
23/23 - 0s - 13ms/step - loss: 1561.7780 - val_loss: 1073.6615
Epoch 3/100
23/23 - 0s - 16ms/step - loss: 1391.0399 - val_loss: 902.0388
Epoch 4/100
23/23 - 0s - 12ms/step - loss: 1119.6102 - val_loss: 667.2036
Epoch 5/100
23/23 - 0s - 12ms/step - loss: 773.6013 - val_loss: 431.6924
Epoch 6/100
23/23 - 0s - 11ms/step - loss: 470.6923 - val_loss: 268.9634
Epoch 7/100
23/23 - 0s - 17ms/step - loss: 307.5588 - val_loss: 210.2917
Epoch 8/100
23/23 - 0s - 13ms/step - loss: 246.5506 - val_loss: 188.2529
Epoch 9/100
23/23 - 0s - 20ms/step - loss: 220.5235 - val_loss: 180.1965
Epoch 10/100
23/23 - 0s - 14ms/step - loss: 205.2228 - val_loss: 172.1992
Epoch 11/100
23/23 - 0s - 19ms/step - loss: 194.2262 - val_loss: 171.5566
Epoch 12/100
23/23 - 0s - 12ms/step - loss: 186.0133 - val_loss: 170.7172
Epoch 13/100
23/23 - 0s - 17ms/step - loss: 179.7570 - val_loss: 167.1105
Epoch 14/100
23/23 - 0s - 20ms/step - loss: 174.1642 - val_loss: 165.4892
Epoch 15/100
23/23 - 1s - 30ms/step - loss: 169.8845 - val_loss: 164.4576
Epoch 16/100
23/23 - 0s - 15ms/step - loss: 164.8087 - val_loss: 163.8906
Epoch 17/100
23/23 - 1s - 22ms/step - loss: 161.6475 - val_loss: 163.0399
Epoch 18/100
23/23 - 0s - 21ms/step - loss: 158.7874 - val_loss: 159.7760
Epoch 19/100
23/23 - 0s - 12ms/step - loss: 156.5811 - val_loss: 160.2952
Epoch 20/100
23/23 - 0s - 17ms/step - loss: 153.5735 - val_loss: 159.8528
Epoch 21/100
23/23 - 0s - 12ms/step - loss: 151.7784 - val_loss: 157.3859
Epoch 22/100
23/23 - 0s - 15ms/step - loss: 148.9732 - val_loss: 157.7259
Epoch 23/100
23/23 - 1s - 28ms/step - loss: 146.8683 - val_loss: 158.1876
Epoch 24/100
23/23 - 0s - 14ms/step - loss: 144.9846 - val_loss: 157.3268
Epoch 25/100
23/23 - 0s - 12ms/step - loss: 143.3957 - val_loss: 156.8349
Epoch 26/100
23/23 - 0s - 15ms/step - loss: 142.1238 - val_loss: 154.6833
Epoch 27/100
23/23 - 0s - 12ms/step - loss: 140.5060 - val_loss: 153.5138
Epoch 28/100
23/23 - 0s - 13ms/step - loss: 138.5346 - val_loss: 158.0239
Epoch 29/100
23/23 - 0s - 17ms/step - loss: 137.1582 - val_loss: 152.2760
Epoch 30/100
23/23 - 0s - 12ms/step - loss: 135.4790 - val_loss: 153.6394
Epoch 31/100
23/23 - 0s - 11ms/step - loss: 134.5282 - val_loss: 154.4671
Epoch 32/100
23/23 - 0s - 14ms/step - loss: 132.8745 - val_loss: 154.5198
Epoch 33/100
23/23 - 0s - 13ms/step - loss: 131.3461 - val_loss: 152.8444
Epoch 34/100
23/23 - 0s - 11ms/step - loss: 129.7760 - val_loss: 150.1146
Epoch 35/100
23/23 - 0s - 16ms/step - loss: 128.4609 - val_loss: 152.6068
Epoch 36/100
23/23 - 0s - 14ms/step - loss: 126.4662 - val_loss: 152.9850
Epoch 37/100
23/23 - 0s - 12ms/step - loss: 124.9794 - val_loss: 149.7867
Epoch 38/100
23/23 - 0s - 15ms/step - loss: 123.1111 - val_loss: 151.0058
Epoch 39/100
23/23 - 1s - 29ms/step - loss: 122.0906 - val_loss: 148.6017
Epoch 40/100
23/23 - 0s - 15ms/step - loss: 119.6658 - val_loss: 149.3923
Epoch 41/100
23/23 - 0s - 14ms/step - loss: 117.6143 - val_loss: 146.6498
Epoch 42/100
23/23 - 0s - 16ms/step - loss: 115.4859 - val_loss: 145.9169
Epoch 43/100
23/23 - 1s - 28ms/step - loss: 113.5021 - val_loss: 143.2834
Epoch 44/100
23/23 - 0s - 14ms/step - loss: 111.2625 - val_loss: 141.8754
Epoch 45/100
23/23 - 0s - 12ms/step - loss: 109.1356 - val_loss: 141.7904
Epoch 46/100
23/23 - 1s - 34ms/step - loss: 106.9344 - val_loss: 137.6235
Epoch 47/100
23/23 - 0s - 15ms/step - loss: 104.9324 - val_loss: 139.9000
Epoch 48/100
23/23 - 0s - 14ms/step - loss: 102.9753 - val_loss: 137.3111
Epoch 49/100
23/23 - 0s - 15ms/step - loss: 98.5492 - val_loss: 130.4307
Epoch 50/100
23/23 - 0s - 14ms/step - loss: 96.4419 - val_loss: 125.4214
Epoch 51/100
23/23 - 0s - 11ms/step - loss: 92.8922 - val_loss: 127.4426
Epoch 52/100
23/23 - 0s - 14ms/step - loss: 89.5207 - val_loss: 125.7371
Epoch 53/100
23/23 - 1s - 28ms/step - loss: 86.7663 - val_loss: 122.2649
Epoch 54/100
23/23 - 0s - 13ms/step - loss: 83.1450 - val_loss: 121.8933
Epoch 55/100
23/23 - 0s - 11ms/step - loss: 79.6555 - val_loss: 117.3348
Epoch 56/100
23/23 - 0s - 18ms/step - loss: 76.5047 - val_loss: 114.2606
Epoch 57/100
23/23 - 0s - 12ms/step - loss: 73.2513 - val_loss: 117.8076
Epoch 58/100
23/23 - 0s - 13ms/step - loss: 70.3101 - val_loss: 108.6048
Epoch 59/100
23/23 - 0s - 14ms/step - loss: 67.1567 - val_loss: 115.8198
Epoch 60/100
23/23 - 0s - 12ms/step - loss: 65.3725 - val_loss: 107.7921
Epoch 61/100
23/23 - 0s - 18ms/step - loss: 62.0228 - val_loss: 103.5106
Epoch 62/100
23/23 - 0s - 14ms/step - loss: 60.3715 - val_loss: 114.0825
Epoch 63/100
23/23 - 0s - 17ms/step - loss: 57.6063 - val_loss: 103.5342
Epoch 64/100
23/23 - 0s - 13ms/step - loss: 55.6956 - val_loss: 101.8502
Epoch 65/100
23/23 - 0s - 12ms/step - loss: 53.7267 - val_loss: 107.2642
Epoch 66/100
23/23 - 0s - 15ms/step - loss: 52.8278 - val_loss: 101.4602
Epoch 67/100
23/23 - 0s - 12ms/step - loss: 51.1235 - val_loss: 94.7691
Epoch 68/100
23/23 - 0s - 14ms/step - loss: 50.1488 - val_loss: 105.1321
Epoch 69/100
23/23 - 0s - 13ms/step - loss: 48.3440 - val_loss: 103.5236
Epoch 70/100
23/23 - 0s - 18ms/step - loss: 47.0296 - val_loss: 101.8937
Epoch 71/100
23/23 - 1s - 28ms/step - loss: 45.7238 - val_loss: 102.1859
Epoch 72/100
23/23 - 0s - 12ms/step - loss: 44.6216 - val_loss: 103.6114
Epoch 73/100
23/23 - 0s - 13ms/step - loss: 43.6118 - val_loss: 102.4218
Epoch 74/100
23/23 - 0s - 15ms/step - loss: 42.7814 - val_loss: 101.7572
Epoch 75/100
23/23 - 0s - 15ms/step - loss: 43.1125 - val_loss: 107.1757
Epoch 76/100
23/23 - 0s - 18ms/step - loss: 41.3130 - val_loss: 105.0218
Epoch 77/100
23/23 - 0s - 18ms/step - loss: 40.5052 - val_loss: 110.3242
Epoch 78/100
23/23 - 0s - 13ms/step - loss: 39.9193 - val_loss: 103.7595
Epoch 79/100
23/23 - 0s - 13ms/step - loss: 39.0947 - val_loss: 106.1669
Epoch 80/100
23/23 - 0s - 14ms/step - loss: 38.4608 - val_loss: 101.6772
Epoch 81/100
23/23 - 0s - 13ms/step - loss: 37.6273 - val_loss: 97.4172
Epoch 82/100
23/23 - 0s - 17ms/step - loss: 37.2790 - val_loss: 102.3362
Epoch 83/100
23/23 - 0s - 14ms/step - loss: 36.8445 - val_loss: 104.7569
Epoch 84/100
23/23 - 0s - 15ms/step - loss: 36.3083 - val_loss: 97.7977
Epoch 85/100
23/23 - 0s - 13ms/step - loss: 36.3212 - val_loss: 99.8889
Epoch 86/100
23/23 - 0s - 14ms/step - loss: 35.0522 - val_loss: 107.1082
Epoch 87/100
23/23 - 0s - 12ms/step - loss: 34.8090 - val_loss: 105.7301
Epoch 88/100
23/23 - 0s - 14ms/step - loss: 34.1134 - val_loss: 104.7884
Epoch 89/100
23/23 - 0s - 13ms/step - loss: 34.6181 - val_loss: 104.4473
Epoch 90/100
23/23 - 0s - 15ms/step - loss: 34.1175 - val_loss: 112.3486
Epoch 91/100
23/23 - 0s - 14ms/step - loss: 33.2234 - val_loss: 103.2402
Epoch 92/100
23/23 - 0s - 19ms/step - loss: 33.1319 - val_loss: 111.5452
Epoch 93/100
23/23 - 1s - 24ms/step - loss: 32.6522 - val_loss: 113.3484
Epoch 94/100
23/23 - 0s - 12ms/step - loss: 32.1461 - val_loss: 104.6859
Epoch 95/100
23/23 - 0s - 11ms/step - loss: 32.1927 - val_loss: 111.2063
Epoch 96/100
23/23 - 0s - 14ms/step - loss: 31.4548 - val_loss: 112.7241
Epoch 97/100
23/23 - 0s - 13ms/step - loss: 31.3969 - val_loss: 108.6044
Epoch 98/100
23/23 - 0s - 13ms/step - loss: 30.8289 - val_loss: 104.8122
Epoch 99/100
23/23 - 1s - 23ms/step - loss: 31.3574 - val_loss: 111.5540
Epoch 100/100
23/23 - 0s - 12ms/step - loss: 30.8118 - val_loss: 113.7537